import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
TICKERS_FILE = BASE_DIR / "tickers.txt"
DOCS_DIR = BASE_DIR / "docs"
DATA_DIR = DOCS_DIR / "data"
STRATEGIES_DIR = BASE_DIR / "strategies"

LATEST_JSON = DATA_DIR / "latest.json"
HISTORY_JSON = DATA_DIR / "history.json"
PINE_FILE = STRATEGIES_DIR / "breakout_surge_v6.pine"

LOOKBACK_DAYS = 380
INTERVAL = "1d"
SHARD_SIZE = 50
MAX_WORKERS = 10

SURGE_THRESHOLD = 0.05
MIN_TRAINING_SAMPLES = 1000
K_FOLDS = 5
TEST_SIZE_RATIO = 0.20
TARGET_SPECIFICITY = 0.95

MAX_TUNING_SAMPLES = 120000
HYPERPARAM_SEARCH_ITER = 8
RANDOM_STATE = 42

TARGET_1_PCT = 0.05
TARGET_2_PCT = 0.10
TARGET_3_PCT = 0.18
ATR_SL_MULTIPLIER = 1.5
MAX_SL_PCT = 0.04
